"""add relation project client

Revision ID: 7d93f2a459d6
Revises: 49a15d7f61f8
Create Date: 2018-03-15 17:51:35.632749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d93f2a459d6'
down_revision = '49a15d7f61f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('client_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'project', 'client', ['client_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project', type_='foreignkey')
    op.drop_column('project', 'client_id')
    # ### end Alembic commands ###
